name: Liquibase_Docker_Hosted

on:
   workflow_dispatch:
#  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RunChecks:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changeLog.h2.sql --username=admin --password=password checks show
    
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changeLog.h2.sql --username=admin --password=password checks run
