name: Liquibase_RUN_PRO_CHECKS

on:
   workflow_dispatch:
#  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RunChecks:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase checks show' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changelog.h2.sql --username=admin --password=password checks show
    
    - name: Run 'Liquibase checks run' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changelog.h2.sql --username=admin --password=password checks run
