name: Liquibase_RUN_FLOWFILE

on:
   workflow_dispatch:
#  push:
#    branches: [ main ]
   pull_request:
#     branches: [ main ]
# Copy Environment variables for use here
env:
   LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
   LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
   LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
   LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
   LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
#    LIQUIBASE_HUB_API_KEY: ${{ secrets.LIQUIBASE_HUB_API_KEY }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RunChecks:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase flow' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: flow --flow-file=liquibase.flowfile.yaml
